import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import MobileNavigation from "@/components/navbar/MobileNavigation";
import MenuProvider from "@/providers/MenuProvider";

const century_gothic = localFont({
  src: [
    {
      path: "./font/CenturyGothic/centurygothic.ttf",
      weight: "300",
      style: "regular",
    },
    {
      path: "./font/CenturyGothic/centurygothic_bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Two Palms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${century_gothic.className} relative antialiased bg-white`}>
        <MenuProvider>
          <Navbar />
          <MobileNavigation />
          {children}
          <Footer />
        </MenuProvider>
      </body>
    </html>
  );
}
